server:
  port: 8084

spring:
  application:
    name: fs-client
  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: health,info

# application.yml
grpc:
  client:
    grpc-tunnel-client:  # 定义一个channel
      address: static://localhost:9090
      negotiation-type: plaintext
  tunnel:
    client:
      enabled: true
      channel-name: "grpc-tunnel-client"  # 引用上面定义的channel

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.loadbalancer: TRACE
    reactor.netty.http.client: DEBUG
